const KEY='tm_assignment_state_v1';
const fallbackImg='https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&q=85';
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{country:'US',profile:{name:'',email:'',phone:''},events:[{id:'bts-demo',eventName:"BTS WORLD TOUR 'ARIRANG' IN TORONTO",artistName:'BTS',tourName:"BTS WORLD TOUR 'ARIRANG'",date:'2026-08-23',time:'20:00',venue:'Rogers Stadium',location:'Toronto, ON',image:fallbackImg,order:'29000601112694497',ticketType:'Mobile Ticket',entry:'Gate 3',purchaseDate:'2026-06-01',notes:'',tickets:[{section:'N110',row:'24',seat:'14',barcode:'29000601112694497001'}]}]};
function save(){localStorage.setItem(KEY,JSON.stringify(state))} function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))} function app(){return document.getElementById('app')} function modal(){return document.getElementById('modal')}
const countries=[['US','🇺🇸','United States'],['NG','🇳🇬','Nigeria'],['CA','🇨🇦','Canada'],['GB','🇬🇧','United Kingdom'],['AU','🇦🇺','Australia'],['BE','🇧🇪','Belgium'],['DE','🇩🇪','Germany'],['ES','🇪🇸','Spain'],['FR','🇫🇷','France'],['IE','🇮🇪','Ireland'],['MX','🇲🇽','Mexico'],['NL','🇳🇱','Netherlands'],['NZ','🇳🇿','New Zealand'],['ZA','🇿🇦','South Africa'],['SE','🇸🇪','Sweden'],['CH','🇨🇭','Switzerland'],['AE','🇦🇪','United Arab Emirates']];
function nav(active){return `<nav class="nav">${[['discover','⌕','Discover'],['for-you','♡','Favorites'],['tickets','▱','My Tickets'],['sell','$','Sell'],['account','●','My Account']].map(x=>`<button class="${active===x[0]?'active':''}" onclick="go('${x[0]}')"><span class="ico">${x[1]}</span><span>${x[2]}</span>${x[0]==='account'?'<span class="badge">1</span>':''}</button>`).join('')}</nav>`}
function go(r){location.hash='#/'+r} function route(){return location.hash.replace('#/','')||'discover'}
function render(body,active,cls=''){app().innerHTML=`<div class="shell ${cls}">${body}</div>${nav(active)}`}
function discover(){render(`<div class="tm-header"><div class="tm-logo">ticketmaster</div><button class="country" onclick="countriesSheet()">${flag()}</button></div><div class="discover-top"><div class="filters"><button class="filter">Location⌄</button><button class="filter">Dates⌄</button></div><div class="search"><div><small>SEARCH</small><input placeholder="Artist, Event, or Venue" oninput="searchEvents(this.value)"></div><div class="glass">⌕</div></div><div class="cats"><button class="cat">Music</button><button class="cat">Sport</button><button class="cat">Arts, Theatre, & Comedy</button></div></div><div class="featured"><img src="${fallbackImg}"><div class="featured-copy"><h1>WICKED The Musical</h1><button class="blue">Find tickets</button></div></div><div class="white-section"><div class="promo"><img src="${fallbackImg}"><div class="promo-copy"><small>MASTER CARD PRESALE</small><h2>Sages &amp; Spirits</h2></div></div></div>`,`discover`,'dark')}
function flag(){return (countries.find(c=>c[0]===state.country)||countries[0])[1]}
function myTickets(){const ev=state.events;render(`<div class="page-head"><h1>My Events</h1><span class="head-country">${flag()}</span><button class="help">Help</button></div><div class="tabs"><button class="tab active">UPCOMING (${ev.length})</button><button class="tab" onclick="toast('Past events')">PAST (0)</button></div><div class="events">${ev.map(e=>`<article class="event-card"><img src="${esc(e.image||fallbackImg)}"><div class="event-info"><div class="event-date">${dateLabel(e)}</div><h2>${esc(e.eventName)}</h2><p>${esc(e.venue)} - ${esc(e.location)}</p><button class="view" onclick="goEvent('${e.id}')">▱ View Tickets</button></div></article>`).join('')}</div>`,`tickets`)}
function dateLabel(e){if(!e.date)return '';const d=new Date(e.date+'T12:00:00');return d.toLocaleDateString(undefined,{weekday:'short'}).toUpperCase()+' • '+d.toLocaleDateString(undefined,{month:'short'}).toUpperCase()+' '+d.getDate()+', '+d.getFullYear()+' • '+fmtTime(e.time)} function fmtTime(t){if(!t)return '';const [h,m]=t.split(':');let n=+h;const a=n>=12?'PM':'AM';n=n%12||12;return n+':'+m+' '+a}
function goEvent(id){location.hash='#/event/'+encodeURIComponent(id)}
function eventPage(id){const e=state.events.find(x=>x.id===decodeURIComponent(id))||state.events[0];render(`<div class="detail-top"><div class="detail-hero"><img src="${esc(e.image||fallbackImg)}"><button class="back" onclick="go('tickets')">‹</button><button class="help2">Help</button><div class="compact-title">${esc(e.eventName)}<br><span class="muted">${esc(e.venue)}, ${esc(e.location)}</span></div></div><button class="barcode-btn" onclick="entryScreen('${e.id}')">▣ View Tickets</button></div><div class="detail-tabs"><button id="dt-tickets" class="active" onclick="detailTab('tickets')">Tickets</button><button id="dt-extras" onclick="detailTab('extras')">Extras</button></div><div id="detail-body"><div class="order"><div class="order-row"><div><div class="order-id">Order #${esc(e.order)}</div><div class="muted">x${e.tickets.length} Ticket${e.tickets.length===1?'':'s'}</div></div><button>⋮</button></div>${e.tickets.map(t=>`<div class="seat-card"><b>${esc(e.ticketType||'TICKET')}</b><div class="seats" style="margin-top:15px"><div><small>SECTION</small><strong>${esc(t.section)}</strong></div><div><small>ROW</small><strong>${esc(t.row)}</strong></div><div><small>SEAT</small><strong>${esc(t.seat)}</strong></div></div></div>`).join('')}<div class="more">MORE OPTIONS</div><div class="map"><img src="https://tile.openstreetmap.org/17/70455/45143.png"></div><a class="directions" target="_blank" href="https://www.openstreetmap.org/search?query=${encodeURIComponent(e.venue+' '+e.location)}">Get Directions</a><div class="float-actions"><button class="disabled" onclick="toast('Upgrade options')">↥ Upgrade</button><button class="primary" onclick="transferSheet('${e.id}')">↗ Transfer</button><button class="disabled" onclick="toast('Sell options')">⟳ Sell</button></div></div></div>`,`tickets`)}
function detailTab(tab){document.getElementById('dt-tickets').classList.toggle('active',tab==='tickets');document.getElementById('dt-extras').classList.toggle('active',tab==='extras');document.getElementById('detail-body').innerHTML=tab==='extras'?`<div class="extras"><div class="got"><img src="${esc(state.events[0].image||fallbackImg)}"><div class="got-copy"><b>YOU GOT<br>TICKETS!</b></div><div class="share-copy"><h3>Post on Social Media</h3><p>Build hype for the event, and share that you got tickets with your friends and family.</p><button class="blue" onclick="shareGoing()">Share You’re Going</button></div></div></div>`:`<div class="order"><div class="more">MORE OPTIONS</div><div class="map"><img src="https://tile.openstreetmap.org/17/70455/45143.png"></div><a class="directions" href="https://www.openstreetmap.org">Get Directions</a></div>`}
function entryScreen(id){const e=state.events.find(x=>x.id===id)||state.events[0];let idx=0;function draw(){const t=e.tickets[idx];modal().innerHTML=`<div class="sheet"><div class="handle"></div><div style="display:flex;justify-content:space-between"><b>${e.tickets.length} Ticket${e.tickets.length===1?'':'s'}</b><button onclick="closeModal()">Done</button></div><h2>${esc(e.eventName)}</h2><div class="entry-meta"><div><small>SECTION</small><b>${esc(t.section)}</b></div><div><small>ROW</small><b>${esc(t.row)}</b></div><div><small>SEAT</small><b>${esc(t.seat)}</b></div></div><div class="barcode"></div><div class="status">Ticket ${idx+1} of ${e.tickets.length} • Active</div><button class="blue" style="width:100%" onclick="toast('Wallet integration placeholder')">Add to Apple Wallet / Google Wallet</button><div class="two" style="margin-top:12px"><button class="pill" onclick="idx=Math.max(0,idx-1);draw()">Previous</button><button class="pill" onclick="idx=Math.min(e.tickets.length-1,idx+1);draw()">Next</button></div></div>`;modal().classList.add('show')}draw()}
function transferSheet(id){const e=state.events.find(x=>x.id===id);modal().innerHTML=`<div class="sheet"><div class="handle"></div><h2>TRANSFER TICKETS</h2><div class="status">${esc(e.eventName)} • x${e.tickets.length}</div><div class="field"><label>First Name</label><input class="input" id="tf" required></div><div class="field"><label>Last Name</label><input class="input" id="tl" required></div><div class="field"><label>Email</label><input class="input" id="te" type="email" required></div><div class="field"><label>Note</label><textarea class="textarea" id="tn"></textarea></div><button class="blue" style="width:100%" onclick="doTransfer('${id}')">Forward Ticket</button></div>`;modal().classList.add('show')}
function doTransfer(id){const f=document.getElementById('tf').value.trim(),l=document.getElementById('tl').value.trim(),em=document.getElementById('te').value.trim();if(!f||!l||!em){toast('Complete the required fields');return}const e=state.events.find(x=>x.id===id);e.transfer={firstName:f,lastName:l,email:em,status:'Pending',time:new Date().toLocaleString()};save();modal().innerHTML=`<div class="sheet success"><h2>Transfer Pending</h2><p>${esc(f+' '+l)}</p><p class="muted">${esc(em)}</p><div class="status">Pending</div><button class="blue" style="width:100%" onclick="closeModal();goEvent('${id}')">Done</button></div>`}
function forYou(){render(`<div class="page-head"><h1>For You</h1><button class="help">Help</button></div><div class="form"><button class="blue" style="width:100%;margin-bottom:16px" onclick="newEvent()">Add Event</button>${state.events.map((e,i)=>`<div class="seat-edit"><b>${esc(e.eventName)}</b><div class="muted">${esc(e.venue)} • ${esc(e.location)}</div><div style="margin-top:10px"><button class="pill" onclick="editEvent(${i})">Edit</button> <button class="pill" onclick="duplicateEvent(${i})">Duplicate</button> <button class="pill" onclick="deleteEvent(${i})">Delete</button></div></div>`).join('')}</div>`,`for-you`)}
function newEvent(){state.events.push({id:'e'+Date.now(),eventName:'',artistName:'',tourName:'',date:'',time:'',venue:'',location:'',image:fallbackImg,order:'',ticketType:'Mobile Ticket',entry:'',purchaseDate:'',notes:'',tickets:[{section:'',row:'',seat:'',barcode:''}]});save();editEvent(state.events.length-1)}
function editEvent(i){const e=state.events[i];render(`<div class="page-head"><h1>Edit Event</h1><button class="help" onclick="go('for-you')">Done</button></div><div class="form"><div class="field"><label>Event Name</label><input class="input" id="name" value="${esc(e.eventName)}"></div><div class="field"><label>Artist Name</label><input class="input" id="artist" value="${esc(e.artistName)}"></div><div class="field"><label>Tour Name</label><input class="input" id="tour" value="${esc(e.tourName)}"></div><div class="field"><label>Date</label><input class="input" id="date" type="date" value="${esc(e.date)}"></div><div class="field"><label>Time</label><input class="input" id="time" type="time" value="${esc(e.time)}"></div><div class="field"><label>Venue</label><input class="input" id="venue" value="${esc(e.venue)}"></div><div class="field"><label>Location</label><input class="input" id="loc" value="${esc(e.location)}"></div><div class="field"><label>Ticket Type</label><input class="input" id="tt" value="${esc(e.ticketType)}"></div><div class="field"><label>Entry Information</label><input class="input" id="entry" value="${esc(e.entry)}"></div><div class="field"><label>Purchase Date</label><input class="input" id="purchase" type="date" value="${esc(e.purchaseDate)}"></div><div class="field"><label>Order Number</label><input class="input" id="order" value="${esc(e.order)}"></div><div class="field"><label>Ticket Notes</label><textarea class="textarea" id="notes">${esc(e.notes)}</textarea></div><div class="field"><label>Event Banner Image</label><input class="input" id="image" type="file" accept="image/*" onchange="previewImage(this)"></div><div id="seats">${e.tickets.map((t,j)=>seatForm(t,j)).join('')}</div><button class="pill" onclick="addSeat(${i})">+ Add Ticket</button><button class="blue" style="width:100%;margin-top:18px" onclick="saveEdit(${i})">Save Changes</button></div>`,`for-you`)}
function seatForm(t,j){return `<div class="seat-edit"><button class="remove" onclick="removeSeat(${j})">Remove</button><b>Ticket ${j+1}</b><div class="two" style="margin-top:10px"><input class="input" data-seat="${j}" data-k="section" placeholder="Section" value="${esc(t.section)}"><input class="input" data-seat="${j}" data-k="row" placeholder="Row" value="${esc(t.row)}"><input class="input" data-seat="${j}" data-k="seat" placeholder="Seat" value="${esc(t.seat)}"></div></div>`}
function addSeat(i){state.events[i].tickets.push({section:'',row:'',seat:'',barcode:'code'+Date.now()});save();editEvent(i)} function removeSeat(j){if(state.events[0].tickets.length>1){state.events[0].tickets.splice(j,1);save();editEvent(0)}}
function saveEdit(i){const e=state.events[i];for(const id of ['name','artist','tour','date','time','venue','loc','tt','entry','purchase','order','notes'])e[idMap(id)]=document.getElementById(id).value;document.querySelectorAll('[data-seat]').forEach(x=>{e.tickets[+x.dataset.seat][x.dataset.k]=x.value});save();toast('Saved and synchronized');setTimeout(()=>go('tickets'),500)} function idMap(x){return ({name:'eventName',artist:'artistName',tour:'tourName',date:'date',time:'time',venue:'venue',loc:'location',tt:'ticketType',entry:'entry',purchase:'purchaseDate',order:'order',notes:'notes'})[x]}
function previewImage(input){if(!input.files[0])return;const r=new FileReader();r.onload=()=>{state._preview=r.result};r.readAsDataURL(input.files[0])}
function duplicateEvent(i){const e=JSON.parse(JSON.stringify(state.events[i]));e.id='e'+Date.now();e.eventName+=' Copy';state.events.push(e);save();forYou()} function deleteEvent(i){if(state.events.length===1){toast('Keep at least one event');return}state.events.splice(i,1);save();forYou()}
function sell(){render(`<div class="dark" style="min-height:100vh"><div class="page-head"><h1>Sell Tickets</h1></div><div class="form" style="color:#fff"><h1>SELL TICKETS</h1><p>Sell eligible tickets and manage active, sold, and expired listings.</p><button class="blue" style="width:100%;margin:15px 0" onclick="toast('How it works')">Learn How It Works</button>${state.events.map(e=>`<div class="seat-edit" style="color:#111"><b>${esc(e.eventName)}</b><p class="muted">${e.tickets.length} ticket(s) • Eligible to list</p><button class="blue" onclick="toast('Listing created')">Sell Your Tickets</button></div>`).join('')}</div></div>`,`sell`)}
function account(){render(`<div class="page-head"><h1>My Account</h1></div><div class="form"><div class="field"><label>Name</label><input class="input" id="pn" value="${esc(state.profile.name)}"></div><div class="field"><label>Email</label><input class="input" id="pe" value="${esc(state.profile.email)}"></div><div class="field"><label>Phone</label><input class="input" id="pp" value="${esc(state.profile.phone)}"></div><button class="blue" style="width:100%" onclick="saveProfile()">Save Profile</button><div class="list-row">🔔 Notifications <span class="muted">On</span></div><div class="list-row">📍 My Location <span class="muted">${flag()}</span></div><div class="list-row" onclick="countriesSheet()">🌎 My Country / Region <span class="muted">Change</span></div><div class="list-row">♡ Favorite artists</div><div class="list-row">⚙ Security</div><div class="list-row">◐ Preferences</div></div>`,`account`)} function saveProfile(){state.profile={name:document.getElementById('pn').value,email:document.getElementById('pe').value,phone:document.getElementById('pp').value};save();toast('Profile saved')}
function countriesSheet(){modal().innerHTML=`<div class="sheet"><div class="handle"></div><h2>Change Location</h2>${countries.map(c=>`<button class="country-row" onclick="setCountry('${c[0]}')"><span>${c[1]} ${c[2]}</span><span>${state.country===c[0]?'✓':''}</span></button>`).join('')}</div>`;modal().classList.add('show')}
function setCountry(c){state.country=c;save();closeModal();renderRoute()} function closeModal(){modal().className='modal';modal().innerHTML=''} function toast(t){const x=document.createElement('div');x.textContent=t;x.style='position:fixed;left:50%;bottom:92px;transform:translateX(-50%);background:#111;color:#fff;padding:11px 15px;border-radius:999px;z-index:200';document.body.appendChild(x);setTimeout(()=>x.remove(),1800)} function shareGoing(){navigator.share?navigator.share({title:'Going to the event',text:'I got tickets!'}).catch(()=>{}):toast('Share sheet ready')}
function searchEvents(q){/* local search hook */} 
function renderRoute(){const r=route();if(r==='discover')discover();else if(r==='tickets')myTickets();else if(r==='for-you')forYou();else if(r==='sell')sell();else if(r==='account')account();else if(r.startsWith('event/'))eventPage(r.slice(6));else discover()}
window.addEventListener('hashchange',renderRoute);renderRoute();save();
